name: deploy

on:
  push:
    branches:
      - main

jobs:
  push-to-production:
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Sed Config Base
      #   shell: bash
      #   run: |
      #     sed -i  's#VITE_PUBLIC_PATH\s*=.*#VITE_PUBLIC_PATH = /banquet-admin/#g' ./.env.production
      #     sed -i  "s#VITE_BUILD_COMPRESS\s*=.*#VITE_BUILD_COMPRESS = 'gzip'#g" ./.env.production
      #     cat ./.env.production

      - name: use Node.js 16
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          yarn install
          yarn run build
          touch dist/.nojekyll
          cp dist/index.html dist/404.html

      - name: rsync productions
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: /usr/share/www
          remote_host: 47.108.177.221
          remote_user: root
          remote_key: ${{ secrets.REMOTE_KEY }}
